package updater.structure;

public enum LegalForm {SPÓ£KA_ZOO,SPÓ£KA_KOMANDYTOWA,SPÓ£KA_JAWNA,SPÓ£KA_AKCYJNA, SPÓ£KA_CYWILNA,SPÓ£KA_KOMANDYTOWO_AKCYJNA,SPÓ£KA_PARTNERSKA,INSTYTUT,DZIA£ALNOŒÆ_GOSPODARCZA,ZWIAZEK_PRODUCENTÓW_ROLNYCH,
	FUNDACJA,STOWARZYSZENIE,JENOSTKA_OŒWIATY,JEDNOSTKA_BADAWCZO_ROZWOJOWA, ZWI¥ZEK_PRACODAWCÓW, ORGANIZACJA_SPO£ECZNA, SPÓ£DZIELNIA,ZWI¥ZEK_WYZNANIOWY, PRZEDSIÊBIORSTWO_PAÑSTWOWE, TOWARZYSTWO, SAMORZ¥D_GOSPODARCZY,
	JEDNOOSOBOWA_W£ASNOŒÆ_PRYWATNA, ODDZIA£_PRZEDSIÊBIORCY_ZAGRANICZNEGO, ZWI¥ZEK_GRUP_PRODUCENTÓW_ROLNYCH, ZWI¥ZEK_ZAWODOWY

}
